version: '3.8'

services:
  postgres_vector:
    image: ankane/pgvector:latest
    container_name: postgres_vector_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      VECTOR_DIMENSIONS: ${VECTOR_DIMENSIONS}
    ports:
      - "5433:5432" # changed port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - default
      - sip_network

volumes:
  postgres_data:
    driver: local

networks:
  sip_network:
    external: true
